import sys
from pathlib import Path
from ultralytics import YOLO

# Add the project root to the Python path
sys.path.append(str(Path(__file__).resolve().parent.parent))
from src import config

def main():
    print("Initializing training sequence...")
    
    # Load the base pre-trained model (e.g., yolov8n.pt)
    model = YOLO(config.MODEL_PATH)

    # Train the model
    # Note: 'data.yaml' is a file generated by tools like Roboflow that 
    # tells YOLO where your training and validation images are located.
    dataset_yaml_path = str(config.BASE_DIR / "data" / "annotations" / "data.yaml")
    
    results = model.train(
        data=dataset_yaml_path,
        epochs=50,                  # Number of training loops
        imgsz=640,                  # Image size for training
        batch=16,                   # Number of images processed at once
        project=str(config.BASE_DIR / "models"), # Where to save the weights
        name="bag_counter_v1",      # Folder name for the new weights
        device="cpu"                # Change to 0 if you have an NVIDIA GPU
    )
    
    print(f"Training complete. Best weights saved in models/bag_counter_v1/weights/best.pt")

if __name__ == "__main__":
    main()